services:
  - type: web
    name: smart-study-scheduler-api
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: yarn install
    startCommand: yarn start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
